# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='url_id',
            field=models.CharField(default=b'QkKJI', max_length=10),
        ),
    ]
