# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyshare', '0008_writing_user_date'),
    ]

    operations = [
        migrations.RenameModel('Preferences', 'UserInfo')
    ]
