# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 17:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyshare', '0009_auto_20160731_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_goal_met',
            field=models.DateField(default=datetime.date(2016, 7, 31)),
            preserve_default=False,
        ),
    ]
