# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyshare', '0011_auto_20160731_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='last_goal_met',
            field=models.DateField(null=True),
        ),
    ]
