# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writingtracker', '0002_writing_url_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='url_id',
            field=models.CharField(default=b'lSP1E', max_length=10, unique=True),
        ),
    ]
