# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writingtracker', '0005_auto_20160724_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='timezone',
            field=models.CharField(default='US/Eastern', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preferences',
            name='num_words',
            field=models.PositiveIntegerField(),
        ),
    ]
