# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 16:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writingtracker', '0007_auto_20160728_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='user_date',
            field=models.DateField(default=datetime.date(2016, 7, 30)),
            preserve_default=False,
        ),
    ]
