# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 19:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('writingtracker', '0012_auto_20160731_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_reset',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 13, 19, 6, 14, 536267, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='last_goal_met',
            field=models.DateField(blank=True, null=True),
        ),
    ]
